name: Update My EPG

on:
  schedule:
    - cron: '0 */6 * * *' # Jalan setiap 6 jam
  workflow_dispatch:      # Tombol manual jika ingin update mendadak

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run grabber
        run: python grabber.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add my_epg.xml
          git commit -m "Update EPG: $(date)" || exit 0
          git push
